from LEDsetup import*
while(True):
    led.fill(Green)
    time.sleep(0.5)
    led.update()
    led.fill(Off)
    led.fill(Pink)
    time.sleep(0.5)
    led.update()
    led.fill(Brown)
    time.sleep(0.5)
    led.fill(Yellow)
    time.sleep(0.5)
    led.update()
    led.fill(Gold)
    time.sleep(0.5)
    led.update()
    led.fill(Maroon)
    time.sleep(0.5)
    led.update()
    
